name: victoralonsolion
favicon: null
layout_spectrum: 0.22985321399755776
typography_spectrum: 0.25431111990474164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1459401415195316
  lightness: 0.27907128166407347
  saturation: 0.6360712738242
  rhythmicContrast: 0.28585196239873767
purpose: []
